print("I put my trust in you")
print("Pushed as far as I can go")
print("For all this")
print("There's only one thing you should know")
print("I try so hard")
print("And got so far")
print("But in the end", end="")
print("It doesn't even matter")
print("I had to fall")
print("To lose it all")
print("But in the end", end="")
print("It doesn't even matter")
